### ISSUE TITLE
Failed to initialize the store cipher

### ISSUE THREAD

**Issue by jlxq0** [etkecc/baibot#1]
I'm just trying to connect the baibot to my own matrix instance and I'm stuck here:

```
> k logs pod/ksc-matrix-baibot-67c875cb4f-rvpp6                                                                                                                                                                              
2024-09-13T10:46:06.921513Z  INFO ThreadId(01) mxlink::init: /cargo/registry/src/index.crates.io-6f17d22bba15001f/mxlink-1.0.0/src/init.rs:123: Creating a brand new client
Error: Error creating a new login session: Error building the client: Failed to initialize the store cipher
```

Any hints?

P.S.: Thank you for your awesome work!

**Comment by spantaleev** [comment]
This is more of a symptom of a previous failed startup. When initialization fails (due to "incorrect login or password" or similar error), matrix-rust-sdk would leave behind some corrupt database and a "Failed to initialize the store cipher" would happen if it's tried to be reused.

mxlink can now auto-recover from similar trouble thanks to a fix done via https://github.com/etkecc/rust-mxlink/commit/f339fc85e69aa7f614394ad303d1614cd307319c.

The fix is part of the v1.0.3 (and `:latest`) release of baibot.
